export const GRAPH_FILTER_STATE = "GRAPH_FILTER_STATE";
export const SET_ROUTE = "SET_ROUTE";
export const INFLUENCERS_TYPE = "INFLUENCERS_TYPE";

/* Subject Carousel */
export const RESET_CAROUSEL = "RESET_CAROUSEL";
export const REQUEST_SUBJECTS = "REQUEST_SUBJECTS";
export const RECEIVE_SUBJECTS = "RECEIVE_SUBJECTS";
export const SLIDE_CAROUSEL = "SLIDE_CAROUSEL";
export const SETUP_CAROUSEL = "SETUP_CAROUSEL";

/* Login */
export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const REQUEST_LOGOUT = "REQUEST_LOGOUT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

/* Reporting */
export const REQUEST_DOWNLOAD_REPORT = "REQUEST_DOWNLOAD_REPORT";
export const RECEIVE_DOWNLOAD_REPORT = "RECEIVE_DOWNLOAD_REPORT";

/* Application */
export const HYDRATE_APP = "HYDRATE_APP";

/* Socket */
export const SOCKET_SYNC_USER = "SOCKET_SYNC_USER";
export const SOCKET_ROOM_NOTIFICATION = "SOCKET_ROOM_NOTIFICATION";

/* Admin */
export const REQUEST_TEAMS = "REQUEST_TEAM_LIST";
export const RECEIVE_TEAMS = "RECEIVE_TEAM_LIST";
export const REQUEST_ADD_TEAM = "REQUEST_ADD_TEAM";
export const RECEIVE_ADD_TEAM = "RECEIEVE_ADD_TEAM";
export const REQUEST_EDIT_TEAM = "REQUEST_EDIT_TEAM";
export const RECEIVE_EDIT_TEAM = "RECEIVE_EDIT_TEAM";
export const REQUEST_DELETE_TEAM = "REQUEST_DELETE_TEAM";

/* Admin Slider */
export const OPEN_ADMIN_SLIDER = "OPEN_ADMIN_SLIDER";
export const CLOSE_ADMIN_SLIDER = "CLOSE_ADMIN_SLIDER";
