export const GRAPH_FILTER_STATE = "GRAPH_FILTER_STATE";
export const SET_ROUTE = "SET_ROUTE";
export const INFLUENCERS_TYPE = "INFLUENCERS_TYPE";

/* Subject Carousel */
export const RESET_CAROUSEL = "RESET_CAROUSEL";
export const REQUEST_SUBJECTS = "REQUEST_SUBJECTS";
export const RECEIVE_SUBJECTS = "RECEIVE_SUBJECTS";
export const SLIDE_CAROUSEL = "SLIDE_CAROUSEL";
export const SETUP_CAROUSEL = "SETUP_CAROUSEL";

/* Login */
export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
